export const attributes = [
    {
      label: "Estilo do Avatar",
      attribute: "avatarStyle",
      value: ["Circle", "Transparent"],
    },
    {
      label: "Estilo do Cabelo",
      attribute: "topType",
      value: [
        "NoHair",
        "Eyepatch",
        "Hat",
        "LongHairBigHair",
        "LongHairBob",
        "LongHairBun",
        "LongHairCurly",
        "LongHairCurvy",
        "LongHairDreads",
        "LongHairFrida",
        "LongHairFro",
        "LongHairFroBand",
        "LongHairNotTooLong",
        "LongHairShavedSides",
        "LongHairMiaWallace",
        "LongHairStraight",
        "LongHairStraight2",
        "LongHairStraightStrand",
        "ShortHairDreads02",
        "ShortHairFrizzle",
        "ShortHairShaggyMullet",
        "ShortHairShortCurly",
        "ShortHairShortFlat",
        "ShortHairShortRound",
        "ShortHairShortWaved",
        "ShortHairSides",
        "ShortHairTheCaesar",
        "ShortHairTheCaesarSidePart",
      ],
    },
    {
      label: "Acessórios",
      attribute: "accessoriesType",
      value: [
        "Blank",
        "Kurt",
        "Prescription01",
        "Prescription02",
        "Round",
        "Sunglasses",
      ],
    },
    {
      label: "Cor do Cabelo",
      attribute: "hairColor",
      value: [
        "Auburn",
        "Black",
        "Blonde",
        "BlondeGolden",
        "Brown",
        "BrownDark",
        "PastelPink",
        "Blue",
        "Platinum",
        "Red",
        "SilverGray",
      ],
    },
    {
      label: "Barba",
      attribute: "facialHairType",
      value: [
        "Blank",
        "BeardMedium",
        "BeardLight",
        "BeardMajestic",
        "MoustacheFancy",
        "MoustacheMagnum",
      ],
    },
    {
      label: "Cor do Barba",
      attribute: "facialHairColor",
      value: [
        "Auburn",
        "Black",
        "Blonde",
        "BlondeGolden",
        "Brown",
        "BrownDark",
        "PastelPink",
        "Blue",
        "Platinum",
        "Red",
      ],
    },
    {
      label: "Roupa",
      attribute: "clotheType",
      value: [
        "BlazerShirt",
        "BlazerSweater",
        "CollarSweater",
        "GraphicShirt",
        "Hoodie",
        "Overall",
        "ShirtCrewNeck",
        "ShirtScoopNeck",
        "ShirtVNeck",
      ],
    },
    {
      label: "Cor da Roupa",
      attribute: "clotheColor",
      value: [
        "Black",
        "Blue01",
        "Blue02",
        "Blue03",
        "Gray01",
        "Gray02",
        "Heather",
        "PastelBlue",
        "PastelGreen",
        "PastelOrange",
        "PastelRed",
        "PastelYellow",
        "Pink",
        "Red",
        "White",
      ],
    },
    {
      label: "Olhos",
      attribute: "eyeType",
      value: [
        "Close",
        "Cry",
        "Default",
        "Dizzy",
        "EyeRoll",
        "Happy",
        "Hearts",
        "Side",
        "Squint",
        "Surprised",
        "Wink",
        "WinkWacky",
      ],
    },
    {
      label: "Sobrancelhas",
      attribute: "eyebrowType",
      value: [
        "Angry",
        "AngryNatural",
        "Default",
        "DefaultNatural",
        "FlatNatural",
        "RaisedExcited",
        "RaisedExcitedNatural",
        "SadConcerned",
        "SadConcernedNatural",
        "UnibrowNatural",
        "UpDown",
        "UpDownNatural",
      ],
    },
    {
      label: "Boca",
      attribute: "mouthType",
      value: [
        "Concerned",
        "Default",
        "Disbelief",
        "Eating",
        "Grimace",
        "Sad",
        "ScreamOpen",
        "Serious",
        "Smile",
        "Tongue",
        "Twinkle",
        "Vomit",
      ],
    },
    {
      label: "Cor da Pele",
      attribute: "skinColor",
      value: [
        "Tanned",
        "Yellow",
        "Pale",
        "Light",
        "Brown",
        "DarkBrown",
        "Black",
      ],
    },
  ];